- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes

- name: Install Packages Needed To Compile PHP 7
  apt: pkg={{ item }} state=latest
  with_items:
        - php7.0-common
        - php7.0-cli
        - php7.0-dev
        - php7.0-fpm
        - libpcre3-dev
        - php7.0-gd
        - php7.0-curl
        - php7.0-imap
        - php7.0-json
        - php7.0-opcache
        - php7.0-xml
        - php7.0-mbstring
        - libapache2-mod-php7.0
        - php7.0-mysql
        - php7.0-mcrypt
        - php7.0-zip
        - php-mongodb
